### ISSUE TITLE
修改--test_img_dirs后除了94x24大小的图片都会报错

### ISSUE THREAD

**Issue by IamWilliamWang** [sirius-ai/LPRNet_Pytorch#17]
除了94x24大小的所有图片都会报这个错，出什么问题了？
> Traceback (most recent call last):
&nbsp;File "test_LPRNet.py", line 176, in <module>
&nbsp;&nbsp;&nbsp;test()
&nbsp;File "test_LPRNet.py", line 74, in test
&nbsp;&nbsp;&nbsp;Greedy_Decode_Eval(lprnet, test_dataset, args)
&nbsp;File "test_LPRNet.py", line 105, in Greedy_Decode_Eval
&nbsp;&nbsp;&nbsp;prebs = Net(images)
&nbsp;File "/home/wang/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
&nbsp;&nbsp;&nbsp;result = self.forward(*input, **kwargs)
&nbsp;File "/home/wang/LPRNet_Pytorch/model/LPRNet.py", line 76, in forward
&nbsp;&nbsp;&nbsp;x = torch.cat(global_context, 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 124 and 28 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:7

**Comment by sirius-ai** [comment]
LPRNet本来就是设计输入大小为94x24的，所以你修改了输入大小后当然会报错了！

**Comment by feitianhouren** [comment]
You can zoom image to "94*24" size.
