### ISSUE TITLE
Problem testing data

### ISSUE THREAD

**Issue by pendex900x** [sirius-ai/LPRNet_Pytorch#30]
When I use `python test_LPRNet.py` the output:

```
Successful to build network!
load pretrained model successful!
Traceback (most recent call last):
  File "test_LPRNet.py", line 176, in <module>
    test()
  File "test_LPRNet.py", line 74, in test
    Greedy_Decode_Eval(lprnet, test_dataset, args)
  File "test_LPRNet.py", line 89, in Greedy_Decode_Eval
    images, labels, lengths = next(batch_iterator)
  File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\X\Desktop\LPRNet_Pytorch-master\data\load_data.py", line 40, in __getitem__
    height, width, _ = Image.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```

Why it happends?

**Comment by JKLove21** [comment]
I have met with the same problem！

**Comment by pendex900x** [comment]
Finally I could not solve it:/ please let me know if you find an alternative solution

**Comment by JKLove21** [comment]
Bro, I worked it out! The reason is that opencv cannot read the image file path when it contains Chinese characters

I rewrite a new function as
def cv_imread(file_path):
    cv_img = cv2.imdecode(np.fromfile(file_path, dtype=np.uint8), -1)
    return cv_img
You just need to paste it at the end of load_data.py

Then you substitute the original sentences as follows
filename = self.img_paths[index]
Image = cv_imread(filename)

It will be ok, you can try it

**Comment by pendex900x** [comment]
Wow, I spent hours watching how to fix it and you did it! haha, I got lost in the last part, could you upload the file? I have already created a new function in load_data.py

**Comment by JKLinUESTC** [comment]
This is the new load_data.py
`
from torch.utils.data import *
from imutils import paths
import numpy as np
import random
import cv2
import os


CHARS = ['京', '沪', '津', '渝', '冀', '晋', '蒙', '辽', '吉', '黑',
         '苏', '浙', '皖', '闽', '赣', '鲁', '豫', '鄂', '湘', '粤',
         '桂', '琼', '川', '贵', '云', '藏', '陕', '甘', '青', '宁',
         '新',
         '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
         'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K',
         'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'U', 'V',
         'W', 'X', 'Y', 'Z', 'I', 'O', '-'
         ]

CHARS_DICT = {char:i for i, char in enumerate(CHARS)}

class LPRDataLoader(Dataset):
    def __init__(self, img_dir, imgSize, lpr_max_len, PreprocFun=None):
        self.img_dir = img_dir
        self.img_paths = []
        for i in range(len(img_dir)):
            self.img_paths += [el for el in paths.list_images(img_dir[i])]
        random.shuffle(self.img_paths)
        self.img_size = imgSize
        self.lpr_max_len = lpr_max_len
        if PreprocFun is not None:
            self.PreprocFun = PreprocFun
        else:
            self.PreprocFun = self.transform

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, index):
        filename = self.img_paths[index]
        Image = cv_imread(filename)               # This sentence is modified using the new function below !!
        height, width, _ = Image.shape
        if height != self.img_size[1] or width != self.img_size[0]:
            Image = cv2.resize(Image, self.img_size)
        Image = self.PreprocFun(Image)

        basename = os.path.basename(filename)
        imgname, suffix = os.path.splitext(basename)
        imgname = imgname.split("-")[0].split("_")[0]
        label = list()
        for c in imgname:
            # one_hot_base = np.zeros(len(CHARS))
            # one_hot_base[CHARS_DICT[c]] = 1
            label.append(CHARS_DICT[c])

        if len(label) == 8:
            if self.check(label) == False:
                print(imgname)
                assert 0, "Error label ^~^!!!"

        return Image, label, len(label)

    def transform(self, img):
        img = img.astype('float32')
        img -= 127.5
        img *= 0.0078125
        img = np.transpose(img, (2, 0, 1))

        return img

    def check(self, label):
        if label[2] != CHARS_DICT['D'] and label[2] != CHARS_DICT['F'] \
                and label[-1] != CHARS_DICT['D'] and label[-1] != CHARS_DICT['F']:
            print("Error label, Please check!")
            return False
        else:
            return True

# A new function to replace the cv.imread
def cv_imread(file_path):
    cv_img = cv2.imdecode(np.fromfile(file_path, dtype=np.uint8), -1)
    return cv_img
`

**Comment by JKLinUESTC** [comment]
`from torch.utils.data import *
from imutils import paths
import numpy as np
import random
import cv2
import os


CHARS = ['京', '沪', '津', '渝', '冀', '晋', '蒙', '辽', '吉', '黑',
         '苏', '浙', '皖', '闽', '赣', '鲁', '豫', '鄂', '湘', '粤',
         '桂', '琼', '川', '贵', '云', '藏', '陕', '甘', '青', '宁',
         '新',
         '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
         'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K',
         'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'U', 'V',
         'W', 'X', 'Y', 'Z', 'I', 'O', '-'
         ]

CHARS_DICT = {char:i for i, char in enumerate(CHARS)}

class LPRDataLoader(Dataset):
    def __init__(self, img_dir, imgSize, lpr_max_len, PreprocFun=None):
        self.img_dir = img_dir
        self.img_paths = []
        for i in range(len(img_dir)):
            self.img_paths += [el for el in paths.list_images(img_dir[i])]
        random.shuffle(self.img_paths)
        self.img_size = imgSize
        self.lpr_max_len = lpr_max_len
        if PreprocFun is not None:
            self.PreprocFun = PreprocFun
        else:
            self.PreprocFun = self.transform

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, index):
        filename = self.img_paths[index]
        Image = cv_imread(filename)               # This sentence is modified using the new function below !!
        height, width, _ = Image.shape
        if height != self.img_size[1] or width != self.img_size[0]:
            Image = cv2.resize(Image, self.img_size)
        Image = self.PreprocFun(Image)

        basename = os.path.basename(filename)
        imgname, suffix = os.path.splitext(basename)
        imgname = imgname.split("-")[0].split("_")[0]
        label = list()
        for c in imgname:
            # one_hot_base = np.zeros(len(CHARS))
            # one_hot_base[CHARS_DICT[c]] = 1
            label.append(CHARS_DICT[c])

        if len(label) == 8:
            if self.check(label) == False:
                print(imgname)
                assert 0, "Error label ^~^!!!"

        return Image, label, len(label)

    def transform(self, img):
        img = img.astype('float32')
        img -= 127.5
        img *= 0.0078125
        img = np.transpose(img, (2, 0, 1))

        return img

    def check(self, label):
        if label[2] != CHARS_DICT['D'] and label[2] != CHARS_DICT['F'] \
                and label[-1] != CHARS_DICT['D'] and label[-1] != CHARS_DICT['F']:
            print("Error label, Please check!")
            return False
        else:
            return True

# A new function to replace the cv.imread
def cv_imread(file_path):
    cv_img = cv2.imdecode(np.fromfile(file_path, dtype=np.uint8), -1)
    return cv_img
`

**Comment by JKLinUESTC** [comment]
from torch.utils.data import *
from imutils import paths
import numpy as np
import random
import cv2
import os


CHARS = ['京', '沪', '津', '渝', '冀', '晋', '蒙', '辽', '吉', '黑',
         '苏', '浙', '皖', '闽', '赣', '鲁', '豫', '鄂', '湘', '粤',
         '桂', '琼', '川', '贵', '云', '藏', '陕', '甘', '青', '宁',
         '新',
         '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
         'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K',
         'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'U', 'V',
         'W', 'X', 'Y', 'Z', 'I', 'O', '-'
         ]

CHARS_DICT = {char:i for i, char in enumerate(CHARS)}

class LPRDataLoader(Dataset):
    def __init__(self, img_dir, imgSize, lpr_max_len, PreprocFun=None):
        self.img_dir = img_dir
        self.img_paths = []
        for i in range(len(img_dir)):
            self.img_paths += [el for el in paths.list_images(img_dir[i])]
        random.shuffle(self.img_paths)
        self.img_size = imgSize
        self.lpr_max_len = lpr_max_len
        if PreprocFun is not None:
            self.PreprocFun = PreprocFun
        else:
            self.PreprocFun = self.transform

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, index):
        filename = self.img_paths[index]
        Image = cv_imread(filename)               # This sentence is modified using the new function below !!
        height, width, _ = Image.shape
        if height != self.img_size[1] or width != self.img_size[0]:
            Image = cv2.resize(Image, self.img_size)
        Image = self.PreprocFun(Image)

        basename = os.path.basename(filename)
        imgname, suffix = os.path.splitext(basename)
        imgname = imgname.split("-")[0].split("_")[0]
        label = list()
        for c in imgname:
            # one_hot_base = np.zeros(len(CHARS))
            # one_hot_base[CHARS_DICT[c]] = 1
            label.append(CHARS_DICT[c])

        if len(label) == 8:
            if self.check(label) == False:
                print(imgname)
                assert 0, "Error label ^~^!!!"

        return Image, label, len(label)

    def transform(self, img):
        img = img.astype('float32')
        img -= 127.5
        img *= 0.0078125
        img = np.transpose(img, (2, 0, 1))

        return img

    def check(self, label):
        if label[2] != CHARS_DICT['D'] and label[2] != CHARS_DICT['F'] \
                and label[-1] != CHARS_DICT['D'] and label[-1] != CHARS_DICT['F']:
            print("Error label, Please check!")
            return False
        else:
            return True

# A new function to replace the cv.imread
def cv_imread(file_path):
    cv_img = cv2.imdecode(np.fromfile(file_path, dtype=np.uint8), -1)
    return cv_img

**Comment by JKLove21** [comment]
[load_data.txt](https://github.com/sirius-ai/LPRNet_Pytorch/files/4689686/load_data.txt)

**Comment by JKLove21** [comment]
You can check the txt.

**Comment by pendex900x** [comment]
Thanks, When I try the file  `python test_LPRNet.py`

The output is: 

```
(LPRNet) C:\Users\X\Desktop\LPRNet_Pytorch-master1>python test_LPRNet.py
Successful to build network!
load pretrained model successful!
Traceback (most recent call last):
  File "test_LPRNet.py", line 176, in <module>
    test()
  File "test_LPRNet.py", line 74, in test
    Greedy_Decode_Eval(lprnet, test_dataset, args)
  File "test_LPRNet.py", line 89, in Greedy_Decode_Eval
    images, labels, lengths = next(batch_iterator)
  File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\X\Desktop\LPRNet_Pytorch-master1\data\load_data.py", line 53, in __getitem__
    label.append(CHARS_DICT[c])
KeyError: '皖'
```
[Image](https://prnt.sc/souoo3)

**Comment by pendex900x** [comment]
I think I'm doing something wrong or my computer doesn't have those Chinese character fonts

**Comment by JKLove21** [comment]
Bro, It can work on my computer.&nbsp; I can run the test. py successfully.&nbsp; Your guess maybe right.&nbsp; I think you need to chage the test dataset cause it's Chinese license.&nbsp; Wish you a good luck



---Original---

**Comment by JKLove21** [comment]
My computer has Chinese fonts



---Original---

**Comment by luotianhang** [comment]
an easy... use pil read the image and then use cv to convert the pil,finally you can fix it

**Comment by Moneylijin** [comment]
> [加载数据.txt](https://github.com/sirius-ai/LPRNet_Pytorch/files/4689686/load_data.txt)

thanks

**Comment by Adrian-Yan16** [comment]
> Thanks, When I try the file `python test_LPRNet.py`
> 
> The output is:
> 
> ```
> (LPRNet) C:\Users\X\Desktop\LPRNet_Pytorch-master1>python test_LPRNet.py
> Successful to build network!
> load pretrained model successful!
> Traceback (most recent call last):
>   File "test_LPRNet.py", line 176, in <module>
>     test()
>   File "test_LPRNet.py", line 74, in test
>     Greedy_Decode_Eval(lprnet, test_dataset, args)
>   File "test_LPRNet.py", line 89, in Greedy_Decode_Eval
>     images, labels, lengths = next(batch_iterator)
>   File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
>     return self._process_data(data)
>   File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
>     data.reraise()
>   File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\_utils.py", line 369, in reraise
>     raise self.exc_type(msg)
> KeyError: Caught KeyError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
>     data = fetcher.fetch(index)
>   File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "C:\Users\X\Anaconda3\envs\LPRNet\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "C:\Users\X\Desktop\LPRNet_Pytorch-master1\data\load_data.py", line 53, in __getitem__
>     label.append(CHARS_DICT[c])
> KeyError: '皖'
> ```
> 
> [Image](https://prnt.sc/souoo3)

my keyerror is "y"
