### ISSUE TITLE
cuda runtime error

### ISSUE THREAD

**Issue by guanxiaoguan** [sirius-ai/LPRNet_Pytorch#32]
运行脚本抛出cuda的错误

root@f1248ce5b834:/work/gitlab/LPRNet_Pytorch# python train_LPRNet.py 
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=50 error=30 : unknown error
Traceback (most recent call last):
  File "train_LPRNet.py", line 268, in <module>
    train()
  File "train_LPRNet.py", line 102, in train
    lprnet.to(device)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 425, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 223, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 423, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 197, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCGeneral.cpp:50

我是在docker容器里面训练的,附上我的 nvidia-smi 命令
root@f1248ce5b834:/work/gitlab/LPRNet_Pytorch# nvidia-smi 
Wed Jun 10 17:18:11 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|

请教大神这是什么问题?

**Comment by guanxiaoguan** [comment]
可能真的和docker 容器环境有关,我重启了docker 容器,可以正常训练了
