### ISSUE TITLE
Error in train_LPRNet.py

### ISSUE THREAD

**Issue by saumyapatel17** [sirius-ai/LPRNet_Pytorch#56]
Successful to build network!
initial net weights successful!
Final test Accuracy:
Traceback (most recent call last):
  File "C:\Users\saumy\PycharmProjects\LPRNet_Pytorch-master\train_LPRNet.py", line 268, in <module>
    train()
  File "C:\Users\saumy\PycharmProjects\LPRNet_Pytorch-master\train_LPRNet.py", line 200, in train
    Greedy_Decode_Eval(lprnet, test_dataset, args)
  File "C:\Users\saumy\PycharmProjects\LPRNet_Pytorch-master\train_LPRNet.py", line 208, in Greedy_Decode_Eval
    batch_iterator = iter(DataLoader(datasets, args.test_batch_size, shuffle=True, num_workers=args.num_workers, collate_fn=collate_fn))
  File "C:\Users\saumy\PycharmProjects\LPRNet_Pytorch-master\venv\lib\site-packages\torch\utils\data\dataloader.py", line 270, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "C:\Users\saumy\PycharmProjects\LPRNet_Pytorch-master\venv\lib\site-packages\torch\utils\data\sampler.py", line 102, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by mj-haghighi** [comment]
Hi, Maybe you set the incorrect direction to your images set ...

**Comment by mj-haghighi** [comment]
> Successful to build network!
> initial net weights successful!
> Final test Accuracy:
> Traceback (most recent call last):
> File "C:\Users\saumy\PycharmProjects\LPRNet_Pytorch-master\train_LPRNet.py", line 268, in
> train()
> File "C:\Users\saumy\PycharmProjects\LPRNet_Pytorch-master\train_LPRNet.py", line 200, in train
> Greedy_Decode_Eval(lprnet, test_dataset, args)
> File "C:\Users\saumy\PycharmProjects\LPRNet_Pytorch-master\train_LPRNet.py", line 208, in Greedy_Decode_Eval
> batch_iterator = iter(DataLoader(datasets, args.test_batch_size, shuffle=True, num_workers=args.num_workers, collate_fn=collate_fn))
> File "C:\Users\saumy\PycharmProjects\LPRNet_Pytorch-master\venv\lib\site-packages\torch\utils\data\dataloader.py", line 270, in **init**
> sampler = RandomSampler(dataset, generator=generator) # type: ignore[arg-type]
> File "C:\Users\saumy\PycharmProjects\LPRNet_Pytorch-master\venv\lib\site-packages\torch\utils\data\sampler.py", line 102, in **init**
> raise ValueError("num_samples should be a positive integer "
> ValueError: num_samples should be a positive integer value, but got num_samples=0

Hi, Maybe you set the incorrect direction to your images set ...
