### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by VSERunKNOWN** [sirius-ai/LPRNet_Pytorch#62]
Successful to build network!
load pretrained model successful!
Traceback (most recent call last):
  File "D:LPRNet_Pytorch-master/test_LPRNet.py", line 176, in <module>
    test()
  File "D:LPRNet_Pytorch-master/test_LPRNet.py", line 74, in test
    Greedy_Decode_Eval(lprnet, test_dataset, args)
  File "D:LPRNet_Pytorch-master/test_LPRNet.py", line 137, in Greedy_Decode_Eval
    Acc = Tp * 1.0 / (Tp + Tn_1 + Tn_2)
ZeroDivisionError: float division by zero

**Comment by thamerML** [comment]
did you fix the problem ?? 

i have the same problem

**Comment by superme3322** [comment]
me too, so how to solve this problem
