### ISSUE TITLE
请问这是什么错误？

### ISSUE THREAD

**Issue by zengweigit** [sirius-ai/LPRNet_Pytorch#94]
`Traceback (most recent call last):
  File "/opt/LPRNet_Pytorch/train_LPRNet.py", line 286, in <module>
    train()
  File "/opt/LPRNet_Pytorch/train_LPRNet.py", line 208, in train
    Greedy_Decode_Eval(lprnet, test_dataset, args)
  File "/opt/LPRNet_Pytorch/train_LPRNet.py", line 237, in Greedy_Decode_Eval
    targets = np.array([el.numpy() for el in targets])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (120,) + inhomogeneous part.`

**Comment by zengweigit** [comment]
![image](https://github.com/user-attachments/assets/156a6915-b327-48d9-8b63-a27b003fd32f)

**Comment by IronmanVsThanos** [comment]
> ![image](https://private-user-images.githubusercontent.com/33178471/356186724-156a6915-b327-48d9-8b63-a27b003fd32f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTgyMTQsIm5iZiI6MTcyOTY1NzkxNCwicGF0aCI6Ii8zMzE3ODQ3MS8zNTYxODY3MjQtMTU2YTY5MTUtYjMyNy00OGQ5LThiNjMtYTI3YjAwM2ZkMzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA0MzE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNTIyYTZhZDhhYzhhYWVjNWZiNjVkOGYyNmM2NjZjMmJiZmM2YzU1NTgyNTc1YTljYzQzZjZkMDQ3MGZkYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BnNShoW6mfP9TYxIusX-IFQuOWwAQZjZJarRG1BKvgo)

请问您解决了吗？我也是同样的问题

**Comment by TanakaEmily** [comment]
我也遇到这个问题了，请问有解决吗？

**Comment by yijie-0** [comment]
换一下你的numpy版本，我的环境为python3.9 numpy1.23.0
